PROYEK PBA - KELOMPOK JEBAL


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('menu.csv')

In [10]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [13]:
from sklearn.impute import SimpleImputer


In [14]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')


In [16]:
print(X)

[['Breakfast' 'Egg McMuffin' '4.8 oz (136 g)' ... 10 0 25]
 ['Breakfast' 'Egg White Delight' '4.8 oz (135 g)' ... 6 0 25]
 ['Breakfast' 'Sausage McMuffin' '3.9 oz (111 g)' ... 8 0 25]
 ...
 ['Smoothies & Shakes' 'McFlurry with Oreo Cookies (Snack)'
  '6.7 oz (190 g)' ... 10 0 25]
 ['Smoothies & Shakes'
  "McFlurry with Reese's Peanut Butter Cups (Medium)" '14.2 oz (403 g)'
  ... 20 0 60]
 ['Smoothies & Shakes' "McFlurry with Reese's Peanut Butter Cups (Snack)"
  '7.1 oz (202 g)' ... 10 0 30]]


In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [18]:
print(x)

[[0.0 0.0 1.0 ... 10 0 25]
 [0.0 0.0 1.0 ... 6 0 25]
 [0.0 0.0 1.0 ... 8 0 25]
 ...
 [0.0 0.0 0.0 ... 10 0 25]
 [0.0 0.0 0.0 ... 20 0 60]
 [0.0 0.0 0.0 ... 10 0 30]]


In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [20]:
print(y)

[ 6  4  5  6  5  7  6  7  5  6  6  6  7  7  6  6  6  6  8  6  5  5  6  5
  7  6  8  8  9  6  6 11 11  9  9  6  6  6  1  6  5  5  8  8  9  9  9 10
  6  6  7  8  7  7  7  7  7  7  7  7  7  7  7  6  6  6  6  6  6  6  7  7
  7  7  7  7  7  7  1  2  3  5  8  5  3  4  4  5  6  6  5  5  5  5  5  5
  2  2  4  1  2  0  2  3  4  3  0  4  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  1  0  0  1  0  0  1  0  1  1  0  0  1  0  0  1  0  0
  1  0  0  1  0  1  1  0  0  1  3  3  4  3  3  4  1  1  2  1  1  2  3  3
  4  3  3  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  3  4  2  3
  4  1  1  2  1  1  2  2  2  2  1  1  1  2  2  3  1  1  1  1  2  2  1  1
  1  0  0  0  0  0  0  4  5  6  0  0  4  5  2  4  5  3  3  2]


In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [22]:
print(x_train)

[[0.0 0.0 1.0 ... 0 2 25]
 [0.0 0.0 0.0 ... 0 0 0]
 [0.0 0.0 0.0 ... 0 0 0]
 ...
 [0.0 0.0 0.0 ... 60 15 20]
 [0.0 0.0 0.0 ... 0 30 8]
 [0.0 0.0 1.0 ... 10 2 15]]


In [23]:
print(x_test)

[[0.0 0.0 0.0 ... 2 15 10]
 [0.0 0.0 0.0 ... 25 0 50]
 [0.0 0.0 0.0 ... 20 0 50]
 ...
 [0.0 0.0 1.0 ... 10 10 20]
 [0.0 0.0 0.0 ... 10 0 30]
 [0.0 1.0 0.0 ... 10 4 30]]


In [24]:
print(y_train)

[ 9  0  0  6  6  6  6  0  6  3  1  2  6  9  6  1  1 10  5  5  5  0  6  0
  0  1  3  0  5  7  5  0  0  0  1  0  6  0  1  5  6  7  2  7  0  3  7  3
  0  0  4  0  0  8  6  7  3  0  6  0  0  6  7  1  1  3  2  7  1  4  2  0
  0  0  2  3  8  1  5  2  5  0  1  0  7  1  1  9  1  3  6  4  0  0  0  7
  3  2  0  0  5  0  6  1  0  7  0  6  0  0  9  7  5  2  5  0  4  6  1 11
  0  0  5  2  1  0  2  0  5  0  6  1  4  1  0  0  0  0  6  6  5  4  0  3
  7  8  7  8  7  0  6  1  6  0  0  4  4  6  0  0  0  0  1  5  0  7  0  4
  7  6  7  6  7  5  0  4  2  2  3  3  6  7  0  0  1  1  0  3  0  0  5  3
  6  0  2  7  0  0  0  4  2  0  0  0  4  7  1  6]


In [25]:
print(y_test)

[ 2  0  3  0  3  2  1  3  0  4  8  2  6  4  7  5  5  8  0  2  2  0  0  9
  1  6  9  7  7  0  0  4  0  7  4  1  1  1  0  5  2  0  0  0 11  8  1  1
  1  6  1  0]


In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()


In [29]:
print(x_train)

[[0.0 0.0 1.0 ... 0 2 25]
 [0.0 0.0 0.0 ... 0 0 0]
 [0.0 0.0 0.0 ... 0 0 0]
 ...
 [0.0 0.0 0.0 ... 60 15 20]
 [0.0 0.0 0.0 ... 0 30 8]
 [0.0 0.0 1.0 ... 10 2 15]]


In [30]:
print(x_test)

[[0.0 0.0 0.0 ... 2 15 10]
 [0.0 0.0 0.0 ... 25 0 50]
 [0.0 0.0 0.0 ... 20 0 50]
 ...
 [0.0 0.0 1.0 ... 10 10 20]
 [0.0 0.0 0.0 ... 10 0 30]
 [0.0 1.0 0.0 ... 10 4 30]]
